serverAddr = "<SERVERADDR>"
serverPort = 7000
auth.token = "NZ8WoHRB7l5IaVuk0IJ7"

[[proxies]]
name = "ssh-test"
type = "tcp"
localIP = "192.168.1.3"
localPort = 22
remotePort = 6000

[[proxies]]
name = "web"
type = "http"
localIP = "192.168.1.3"
localPort = 80
customDomains = ["www.yourdomain.com"]